"""Create tables

Revision ID: 1eba99132095
Revises: 
Create Date: 2024-10-26 15:48:46.208619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eba99132095'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=123), nullable=True),
    sa.Column('full_name', sa.String(length=123), nullable=True),
    sa.Column('wallet', sa.Integer(), nullable=True),
    sa.Column('referral', sa.String(length=123), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('user_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=123), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_offers_id'), 'user_offers', ['id'], unique=False)
    op.create_table('user_referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('offered_user_id', sa.Integer(), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offered_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_referrals_id'), 'user_referrals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_referrals_id'), table_name='user_referrals')
    op.drop_table('user_referrals')
    op.drop_index(op.f('ix_user_offers_id'), table_name='user_offers')
    op.drop_table('user_offers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
