"""user role

Revision ID: 504d4b09eece
Revises: 52661f73c311
Create Date: 2024-11-19 16:06:27.337307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '504d4b09eece'
down_revision: Union[str, None] = '52661f73c311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='userrole'),
               type_=sa.String(length=123),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=123),
               type_=postgresql.ENUM('ADMIN', 'USER', name='userrole'),
               existing_nullable=True)
    # ### end Alembic commands ###
